// This script is designed to test the solidity smart contract - SupplyChain.sol -- and the various functions within
// Declare a variable and assign the compiled smart contract artifact
var SupplyChain = artifacts.require("SupplyChain");
const truffleAssert = require("truffle-assertions");

contract("SupplyChain", function (accounts) {
  // Declare few constants and assign a few sample accounts generated by ganache-cli
  var sku = 1;
  var upc = 1;
  const ownerID = accounts[0];
  const originFarmerID = accounts[1];
  const originFarmName = "John Doe";
  const originFarmInformation = "Yarray Valley";
  const originFarmLatitude = "-38.239770";
  const originFarmLongitude = "144.341490";
  var productID = sku + upc;
  const productNotes = "Best caffeine beans for Espresso";
  const productPrice = web3.utils.toWei("1", "ether");
  var itemState = 0;
  const distributorID = accounts[2];
  const retailerID = accounts[3];
  const consumerID = accounts[4];
  const emptyAddress = "0x00000000000000000000000000000000000000";

  ///Available Accounts
  ///==================
  ///(0) 0x27d8d15cbc94527cadf5ec14b69519ae23288b95
  ///(1) 0x018c2dabef4904ecbd7118350a0c54dbeae3549a
  ///(2) 0xce5144391b4ab80668965f2cc4f2cc102380ef0a
  ///(3) 0x460c31107dd048e34971e57da2f99f659add4f02
  ///(4) 0xd37b7b8c62be2fdde8daa9816483aebdbd356088
  ///(5) 0x27f184bdc0e7a931b507ddd689d76dba10514bcb
  ///(6) 0xfe0df793060c49edca5ac9c104dd8e3375349978
  ///(7) 0xbd58a85c96cc6727859d853086fe8560bc137632
  ///(8) 0xe07b5ee5f738b2f87f88b99aac9c64ff1e0c7917
  ///(9) 0xbd3ff2e3aded055244d66544c9c059fa0851da44

  console.log("ganache-cli accounts used here...");
  console.log("Contract Owner: accounts[0] ", accounts[0]);
  console.log("Farmer: accounts[1] ", accounts[1]);
  console.log("Distributor: accounts[2] ", accounts[2]);
  console.log("Retailer: accounts[3] ", accounts[3]);
  console.log("Consumer: accounts[4] ", accounts[4]);

  // 1st Test
  it("Testing smart contract function harvestItem() that allows a farmer to harvest coffee", async () => {
    const supplyChain = await SupplyChain.deployed();
    await supplyChain.addFarmer(originFarmerID);

    // Declare and Initialize a variable for event
    var eventOne = false;

    // Watch the emitted event Harvested()
    supplyChain.Harvested(null, (error, event) => {
      eventOne = true;
    });
    // Mark an item as Harvested by calling function harvestItem()
    let resultOne = await supplyChain.harvestItem(
      upc,
      originFarmerID,
      originFarmName,
      originFarmInformation,
      originFarmLatitude,
      originFarmLongitude,
      productNotes,
      { from: originFarmerID }
    );

    // Retrieve the just now saved item from blockchain by calling function fetchItem()
    const resultBufferOne = await supplyChain.fetchItemBufferOne.call(upc, {
      from: originFarmerID,
    });
    const resultBufferTwo = await supplyChain.fetchItemBufferTwo.call(upc, {
      from: originFarmerID,
    });

    // Verify the result set
    assert.equal(resultBufferOne[0], sku, "E SKU");
    assert.equal(resultBufferOne[1], upc, "E UPC");
    assert.equal(resultBufferOne[2], originFarmerID, "E ownerID");
    assert.equal(resultBufferOne[3], originFarmerID, "E originFarmerID");
    assert.equal(resultBufferOne[4], originFarmName, "E originFarmName");
    assert.equal(
      resultBufferOne[5],
      originFarmInformation,
      "E originFarmInformation"
    );
    assert.equal(
      resultBufferOne[6],
      originFarmLatitude,
      "E originFarmLatitude"
    );
    assert.equal(
      resultBufferOne[7],
      originFarmLongitude,
      "E originFarmLongitude"
    );
    assert.equal(resultBufferTwo[2], productID, "E productID");
    assert.equal(resultBufferTwo[3], productNotes, "E productNotes");
    assert.equal(resultBufferTwo[5], 0, "E State");
    truffleAssert.eventEmitted(resultOne, "Harvested");
  });

  // 2nd Test
  it("Testing smart contract function processItem() that allows a farmer to process coffee", async () => {
    const supplyChain = await SupplyChain.deployed();
    //increment itemState
    itemState++;
    // Declare and Initialize a variable for event
    var eventTwo = false;

    // Watch the emitted event Processed()
    supplyChain.Processed(null, (error, event) => {
      eventTwo = true;
    });

    // Mark an item as Processed by calling function processItem()
    var resultTwo = await supplyChain.processItem(upc, {
      from: originFarmerID,
    });

    // Retrieve the just now saved item from blockchain by calling function fetchItem()
    const resultBufferTwo = await supplyChain.fetchItemBufferTwo.call(upc);

    // Verify the result set
    assert.equal(resultBufferTwo[5], 1, "E L128 state");
    truffleAssert.eventEmitted(resultTwo, "Processed");
  });

  // 3rd Test
  it("Testing smart contract function packItem() that allows a farmer to pack coffee", async () => {
    const supplyChain = await SupplyChain.deployed();
    //increment itemState
    itemState++;
    // Declare and Initialize a variable for event
    let eventThree = false;

    // Watch the emitted event Packed()
    supplyChain.Packed(null, (error, event) => {
      eventThree = true;
    });

    // Mark an item as Packed by calling function packItem()
    const resultThree = await supplyChain.fetchItemBufferTwo.call(upc, {
      from: originFarmerID,
    });

    // Retrieve the just now saved item from blockchain by calling function fetchItem()
    const resultBufferTwo = await supplyChain.fetchItemBufferTwo.call(upc, {
      from: originFarmerID,
    });

    // Verify the result set
    assert.equal(resultBufferTwo[5], itemState, "E L156 state");
    truffleAssert.eventEmitted(resultThree, "Packed");
  });

  // 4th Test
  it("Testing smart contract function sellItem() that allows a farmer to sell coffee", async () => {
    const supplyChain = await SupplyChain.deployed();
    //increment itemState
    itemState++;

    // Declare and Initialize a variable for event
    var eventFour = false;

    // Watch the emitted event ForSale()
    supplyChain.ForSale(null, (error, event) => {
      eventFour = true;
    });

    // Mark an item as ForSale by calling function sellItem()
    var resultFour = await supplyChain.sellItem(upc, productPrice, {
      from: originFarmerID,
    });

    // Retrieve the just now saved item from blockchain by calling function fetchItem()
    const resultBufferTwo = await supplyChain.fetchItemBufferTwo.call(upc, {
      from: originFarmerID,
    });

    // Verify the result set
    assert.equal(resultBufferTwo[4], productPrice, "E L185 productPrice");
    assert.equal(resultBufferTwo[5], itemState, "E L186 state");
    truffleAssert.eventEmitted(resultFour, "ForSale");
  });

  // 5th Test
  it("Testing smart contract function buyItem() that allows a distributor to buy coffee", async () => {
    const supplyChain = await SupplyChain.deployed();
    //increment itemState
    itemState++;

    // Declare and Initialize a variable for event
    var eventFive = false;

    // Watch the emitted event Sold()
    supplyChain.Sold(null, (error, event) => {
      eventFive = true;
    });

    // Mark an item as Sold by calling function buyItem()
    var resultFive = await supplyChain.buyItem(upc, {
      from: distributorID,
      value: productPrice,
    });

    // Retrieve the just now saved item from blockchain by calling function fetchItem()
    const resultBufferOne = await supplyChain.fetchItemBufferOne.call(upc);
    const resultBufferTwo = await supplyChain.fetchItemBufferTwo.call(upc);

    // Verify the result set
    assert.equal(resultBufferOne[2], distributorID, "E L215 ownerID");
    assert.equal(resultBufferTwo[5], 3, "E L216 state");
    assert.equal(resultBufferTwo[6], distributorID, "E L217 distributorID");
    truffleAssert.eventEmitted(resultFive, "Sold");
  });

  // 6th Test
  it("Testing smart contract function shipItem() that allows a distributor to ship coffee", async () => {
    const supplyChain = await SupplyChain.deployed();
    //increment itemState
    itemState++;

    // Declare and Initialize a variable for event
    var eventSix = false;

    // Watch the emitted event Shipped()
    supplyChain.Shipped(null, (error, event) => {
      eventSix = true;
    });

    // Mark an item as Sold by calling function shipItem()
    var resultSix = await supplyChain.shipItem(upc, { from: distributorID });

    // Retrieve the just now saved item from blockchain by calling function fetchItem()
    const resultBufferOne = await supplyChain.fetchItemBufferOne(upc);
    const resultBufferTwo = await supplyChain.fetchItemBufferTwo(upc);

    // Verify the result set
    assert.equal(resultBufferTwo[5], itemState, "E L243 state");
    assert.equal(resultBufferTwo[6], distributorID, "E L244 distributorID");
    truffleAssert.eventEmitted(resultSix, "Shipped");
  });

  // 7th Test
  it("Testing smart contract function receiveItem() that allows a retailer to mark coffee received", async () => {
    const supplyChain = await SupplyChain.deployed();
    await supplyChain.addRetailer(retailerID);
    //increment itemState
    itemState++;

    // Declare and Initialize a variable for event
    let eventSeven = false;

    // Watch the emitted event Received()
    supplyChain.Received(null, (error, event) => {
      eventSeven = true;
    });

    // Mark an item as Sold by calling function receiveItem()
    var resultSeven = await supplyChain.receiveItem(upc, { from: retailerID });

    // Retrieve the just now saved item from blockchain by calling function fetchItem()
    const resultBufferTwo = await supplyChain.fetchItemBufferTwo(upc);

    // Verify the result set
    assert.equal(resultBufferTwo[5], 6, "E L270 state");
    assert.equal(resultBufferTwo[7], retailerID, "E L271 retailerID");
    truffleAssert.eventEmitted(resultSeven, "Received");
  });

  // 8th Test
  it("Testing smart contract function purchaseItem() that allows a consumer to purchase coffee", async () => {
    const supplyChain = await SupplyChain.deployed();
    await supplyChain.addConsumer(consumerID);
    //increment itemState
    itemState++;

    // Declare and Initialize a variable for event
    var eventEight = false;

    // Watch the emitted event Purchased()
    supplyChain.Purchased(null, (error, event) => {
      eventEight = true;
    });

    // Mark an item as Sold by calling function purchaseItem()
    var resultEight = await supplyChain.purchaseItem(upc, { from: consumerID });

    // Retrieve the just now saved item from blockchain by calling function fetchItem()
    const resultBufferOne = await supplyChain.fetchItemBufferOne(upc);
    const resultBufferTwo = await supplyChain.fetchItemBufferTwo(upc);

    // Verify the result set
    assert.equal(resultBufferOne[2], consumerID, "E L298 ownerID");
    assert.equal(resultBufferTwo[5], 7, "E L299 state");
    assert.equal(resultBufferTwo[8], consumerID, "E L300 retailerID");
    truffleAssert.eventEmitted(resultEight, "Purchased");
  });

  // 9th Test
  it("Testing smart contract function fetchItemBufferOne() that allows anyone to fetch item details from blockchain", async () => {
    const supplyChain = await SupplyChain.deployed();

    // Retrieve the just now saved item from blockchain by calling function fetchItem()
    const resultBufferOne = await supplyChain.fetchItemBufferOne(upc);

    // Verify the result set:
    assert.equal(resultBufferOne[0], sku, "E L312 sku");
    assert.equal(resultBufferOne[1], upc, "E L313 upc");
    assert.equal(resultBufferOne[2], consumerID, "E L314 ownerID");
    assert.equal(resultBufferOne[3], originFarmerID, "E L315 originFarmerID");
    assert.equal(resultBufferOne[4], originFarmName, "E L316 originFarmName");
    assert.equal(
      resultBufferOne[5],
      originFarmInformation,
      "E L320 originFarmInformation"
    );
    assert.equal(
      resultBufferOne[6],
      originFarmLatitude,
      "E L325 originFarmLatitude"
    );
    assert.equal(
      resultBufferOne[7],
      originFarmLongitude,
      "E L330: originFarmLongitude"
    );
  });

  // 10th Test
  it("Testing smart contract function fetchItemBufferTwo() that allows anyone to fetch item details from blockchain", async () => {
    const supplyChain = await SupplyChain.deployed();

    // Retrieve the just now saved item from blockchain by calling function fetchItem()
    const resultBufferTwo = await supplyChain.fetchItemBufferOne(upc);

    // Verify the result set:
    assert.equal(resultBufferTwo[0], sku, "E L342 sku");
    assert.equal(resultBufferTwo[1], upc, "E L343 upc");
    assert.equal(resultBufferTwo[2], productID, "E L344 productID");
    assert.equal(resultBufferTwo[3], productNotes, "E L345 productNotes");
    assert.equal(resultBufferTwo[4], productPrice, "E L346 productPrice");
    assert.equal(resultBufferTwo[5], itemState, "E L347 state");
    assert.equal(resultBufferTwo[6], distributorID, "E L348 distributorID");
    assert.equal(resultBufferTwo[7], retailerID, "E L349 retailerID");
    assert.equal(resultBufferTwo[8], consumerID, "E L350 consumerID");
  });
});
